# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_settings_ui.ui'
#
# Created: Mon Sep 15 12:28:24 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_movieSettings(object):
    def setupUi(self, movieSettings):
        movieSettings.setObjectName(_fromUtf8("movieSettings"))
        #movieSettings.resize(249, 343)
        self.gridLayout = QtGui.QGridLayout(movieSettings)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(movieSettings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(movieSettings)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.skipEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipEdit.sizePolicy().hasHeightForWidth())
        self.skipEdit.setSizePolicy(sizePolicy)
        #self.skipEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.skipEdit.setObjectName(_fromUtf8("skipEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.skipEdit)
        self.spsCombo = QtGui.QComboBox(self.groupBox)
        self.spsCombo.setObjectName(_fromUtf8("spsCombo"))
        self.spsCombo.addItem(_fromUtf8(""))
        self.spsCombo.addItem(_fromUtf8(""))
        self.spsCombo.addItem(_fromUtf8(""))
        self.spsCombo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spsCombo)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(movieSettings)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.rangeEdit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeEdit.sizePolicy().hasHeightForWidth())
        self.rangeEdit.setSizePolicy(sizePolicy)
        #self.rangeEdit.setMinimumSize(QtCore.QSize(0, 0))
        #self.rangeEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.rangeEdit.setObjectName(_fromUtf8("rangeEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.rangeEdit)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.errorLabel = QtGui.QLabel(movieSettings)
        self.errorLabel.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.errorLabel.setText(_fromUtf8(""))
        self.errorLabel.setObjectName(_fromUtf8("errorLabel"))
        self.gridLayout.addWidget(self.errorLabel, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(movieSettings)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.timeCombo = QtGui.QComboBox(self.groupBox_3)
        self.timeCombo.setObjectName(_fromUtf8("timeCombo"))
        self.timeCombo.addItem(_fromUtf8(""))
        self.timeCombo.addItem(_fromUtf8(""))
        self.timeCombo.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.timeCombo)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.label.setBuddy(self.spsCombo)
        self.label_2.setBuddy(self.skipEdit)
        self.label_3.setBuddy(self.rangeEdit)
        self.label_4.setBuddy(self.timeCombo)

        self.retranslateUi(movieSettings)
        #QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), movieSettings.accept)
        self.buttonBox.accepted.connect(movieSettings.accept)
        #QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), movieSettings.reject)
        self.buttonBox.rejected.connect(movieSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(movieSettings)

    def retranslateUi(self, movieSettings):
        movieSettings.setWindowTitle(QtGui.QApplication.translate("movieSettings", "Movie settings", None))
        self.groupBox.setTitle(QtGui.QApplication.translate("movieSettings", "Play options", None))
        self.label.setText(QtGui.QApplication.translate("movieSettings", "Slides per second:", None))
        self.label_2.setText(QtGui.QApplication.translate("movieSettings", "Slide skip:", None))
        self.skipEdit.setText(QtGui.QApplication.translate("movieSettings", "0", None))
        self.spsCombo.setItemText(0, QtGui.QApplication.translate("movieSettings", "1", None))
        self.spsCombo.setItemText(1, QtGui.QApplication.translate("movieSettings", "2", None))
        self.spsCombo.setItemText(2, QtGui.QApplication.translate("movieSettings", "4", None))
        self.spsCombo.setItemText(3, QtGui.QApplication.translate("movieSettings", "5", None))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("movieSettings", "Data options", None))
        self.label_3.setText(QtGui.QApplication.translate("movieSettings", "Averaging range:", None))
        self.rangeEdit.setText(QtGui.QApplication.translate("movieSettings", "0", None))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("movieSettings", "Plot options", None))
        self.label_4.setText(QtGui.QApplication.translate("movieSettings", "Title time unit:", None))
        self.timeCombo.setItemText(0, QtGui.QApplication.translate("movieSettings", "original", None))
        self.timeCombo.setItemText(1, QtGui.QApplication.translate("movieSettings", "seconds", None))
        self.timeCombo.setItemText(2, QtGui.QApplication.translate("movieSettings", "milliseconds", None))

