sudo: required
language: python
python:
  - "2.7"
# commands to install dependencies
before_install:
  - ./install_pyqt.sh
install:
  - pip install -r requirements.txt
# command to run tests
script:
  nosetests
