language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - ./install_pyqt.sh
install:
  - pip install -r requirements.txt --use-mirrors
# command to run tests, e.g. python setup.py test
script:
  nosetests
