sudo: required
language: python
python:
  - "2.7"
# commands to install dependencies
before_install:
  - ./install_pyqt.sh
install:
  - pip install -r requirements.txt
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to run tests
script:
  nosetests
