# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created: Tue Jul 28 14:16:32 2015
#      by: PyQt4 UI code generator 4.10.4
#

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName(_fromUtf8("Main"))
        Main.resize(1159, 788)
        self.centralwidget = QtGui.QWidget(Main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.groupBox = QtGui.QGroupBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.plotGrid = MyPlotGrid(self.groupBox)
        self.plotGrid.setObjectName(_fromUtf8("plotGrid"))
        self.gridLayout_5.addWidget(self.plotGrid, 1, 1, 1, 1)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.views = QtGui.QTabWidget(self.splitter)
        self.views.setObjectName(_fromUtf8("views"))
        self.view_1 = MplWidget2d()
        self.view_1.setObjectName(_fromUtf8("view_1"))
        self.views.addTab(self.view_1, _fromUtf8(""))
        self.view_2 = MplWidgetMovie()
        self.view_2.setObjectName(_fromUtf8("view_2"))
        self.views.addTab(self.view_2, _fromUtf8(""))
        self.view_3 = MplWidget3d()
        self.view_3.setObjectName(_fromUtf8("view_3"))
        self.views.addTab(self.view_3, _fromUtf8(""))
        self.view_4 = MplWidgetIsi()
        self.view_4.setObjectName(_fromUtf8("view_4"))
        self.views.addTab(self.view_4, _fromUtf8(""))
        self.view_5 = MplWidgetPCA()
        self.view_5.setObjectName(_fromUtf8("view_5"))
        self.views.addTab(self.view_5, _fromUtf8(""))
        self.tools = QtGui.QTabWidget(self.splitter)
        self.tools.setObjectName(_fromUtf8("tools"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.selector = SelectorWidget(self.tab)
        self.selector.setAutoFillBackground(False)
        self.selector.setStyleSheet(_fromUtf8("background: white"))
        self.selector.setObjectName(_fromUtf8("selector"))
        self.gridLayout_3.addWidget(self.selector, 0, 0, 1, 1)
        self.tools.addTab(self.tab, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.layers = LayerWidget(self.tab2)
        self.layers.setObjectName(_fromUtf8("layers"))
        self.gridLayout_2.addWidget(self.layers, 0, 0, 1, 1)
        self.tools.addTab(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.units = UnitsWidget(self.tab3)
        self.units.setObjectName(_fromUtf8("units"))
        self.gridLayout_4.addWidget(self.units, 0, 0, 1, 1)
        self.tools.addTab(self.tab3, _fromUtf8(""))
        self.tab4 = QtGui.QWidget()
        self.tab4.setObjectName(_fromUtf8("tab4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.details = QtGui.QTableWidget(self.tab4)
        self.details.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.details.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.details.setWordWrap(True)
        self.details.setCornerButtonEnabled(False)
        self.details.setObjectName(_fromUtf8("details"))
        self.details.setColumnCount(1)
        self.details.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.details.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.details.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.details.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.details.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.details.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.details.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.details.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.details.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.details.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.details.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.details.setItem(4, 0, item)
        self.details.horizontalHeader().setStretchLastSection(True)
        self.details.verticalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.details, 0, 0, 1, 1)
        self.tools.addTab(self.tab4, _fromUtf8(""))
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1159, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        Main.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Main)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Main.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(Main)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        Main.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_New_Project = QtGui.QAction(Main)
        self.action_New_Project.setObjectName(_fromUtf8("action_New_Project"))
        self.action_Load_Project = QtGui.QAction(Main)
        self.action_Load_Project.setObjectName(_fromUtf8("action_Load_Project"))
        self.action_Save_Project = QtGui.QAction(Main)
        self.action_Save_Project.setObjectName(_fromUtf8("action_Save_Project"))
        self.action_Quit = QtGui.QAction(Main)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_Swap = QtGui.QAction(Main)
        self.action_Swap.setObjectName(_fromUtf8("action_Swap"))
        self.action_Collapse = QtGui.QAction(Main)
        self.action_Collapse.setObjectName(_fromUtf8("action_Collapse"))
        self.action_Recalculate_mapping = QtGui.QAction(Main)
        self.action_Recalculate_mapping.setObjectName(_fromUtf8("action_Recalculate_mapping"))
        self.action_Save_as = QtGui.QAction(Main)
        self.action_Save_as.setObjectName(_fromUtf8("action_Save_as"))
        self.action_Load_connector_map = QtGui.QAction(Main)
        self.action_Load_connector_map.setObjectName(_fromUtf8("action_Load_connector_map"))
        self.action_Zoom_in = QtGui.QAction(Main)
        self.action_Zoom_in.setObjectName(_fromUtf8("action_Zoom_in"))
        self.action_Zoom_out = QtGui.QAction(Main)
        self.action_Zoom_out.setObjectName(_fromUtf8("action_Zoom_out"))
        self.action_Revert_mapping = QtGui.QAction(Main)
        self.action_Revert_mapping.setObjectName(_fromUtf8("action_Revert_mapping"))
        self.action_Collapse_overview = QtGui.QAction(Main)
        self.action_Collapse_overview.setObjectName(_fromUtf8("action_Collapse_overview"))
        self.action_Expand_overview = QtGui.QAction(Main)
        self.action_Expand_overview.setObjectName(_fromUtf8("action_Expand_overview"))
        self.action_Preferences = QtGui.QAction(Main)
        self.action_Preferences.setObjectName(_fromUtf8("action_Preferences"))
        self.action_About = QtGui.QAction(Main)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.action_Tutorials = QtGui.QAction(Main)
        self.action_Tutorials.setObjectName(_fromUtf8("action_Tutorials"))
        self.action_Virtual_Units = QtGui.QAction(Main)
        self.action_Virtual_Units.setObjectName(_fromUtf8("action_Virtual_Units"))
        self.action_Export_to_csv = QtGui.QAction(Main)
        self.action_Export_to_csv.setObjectName(_fromUtf8("action_Export_to_csv"))
        self.action_Export_to_odML = QtGui.QAction(Main)
        self.action_Export_to_odML.setObjectName(_fromUtf8("action_Export_to_odML"))
        self.action_Import_from_csv = QtGui.QAction(Main)
        self.action_Import_from_csv.setObjectName(_fromUtf8("action_Import_from_csv"))
        self.action_Import_from_odML = QtGui.QAction(Main)
        self.action_Import_from_odML.setObjectName(_fromUtf8("action_Import_from_odML"))
        self.menu_File.addAction(self.action_New_Project)
        self.menu_File.addAction(self.action_Load_Project)
        self.menu_File.addAction(self.action_Save_Project)
        self.menu_File.addAction(self.action_Save_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Load_connector_map)
        self.menu_File.addAction(self.action_Export_to_csv)
        self.menu_File.addAction(self.action_Export_to_odML)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Edit.addAction(self.action_Recalculate_mapping)
        self.menu_Edit.addAction(self.action_Revert_mapping)
        self.menu_Edit.addAction(self.action_Swap)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Zoom_in)
        self.menu_Edit.addAction(self.action_Zoom_out)
        self.menu_Edit.addAction(self.action_Expand_overview)
        self.menu_Edit.addAction(self.action_Collapse_overview)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Preferences)
        self.menu_Help.addAction(self.action_Tutorials)
        self.menu_Help.addAction(self.action_About)
        self.menu_View.addAction(self.action_Virtual_Units)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.action_New_Project)
        self.toolBar.addAction(self.action_Load_Project)
        self.toolBar.addAction(self.action_Save_Project)
        self.toolBar.addAction(self.action_Save_as)
        self.toolBar.addAction(self.action_Preferences)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Revert_mapping)
        self.toolBar.addAction(self.action_Swap)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Zoom_in)
        self.toolBar.addAction(self.action_Zoom_out)
        self.toolBar.addAction(self.action_Expand_overview)
        self.toolBar.addAction(self.action_Collapse_overview)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Virtual_Units)

        self.retranslateUi(Main)
        self.views.setCurrentIndex(0)
        self.tools.setCurrentIndex(0)
        self.action_Quit.triggered.connect(Main.close)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        Main.setWindowTitle(_translate("Main", "SWAN - Sequential waveform analyser", None))
        self.groupBox.setTitle(_translate("Main", "Overview (average of the waveforms)", None))
        self.label.setText(_translate("Main", "SESSIONS", None))
        self.label_2.setText(_translate("Main", "U\n"
"N\n"
"I\n"
"T\n"
"S", None))
        self.views.setTabText(self.views.indexOf(self.view_1), _translate("Main", "2D", None))
        self.views.setTabText(self.views.indexOf(self.view_2), _translate("Main", "Movie", None))
        self.views.setTabText(self.views.indexOf(self.view_3), _translate("Main", "3D", None))
        self.views.setTabText(self.views.indexOf(self.view_4), _translate("Main", "ISI", None))
        self.views.setTabText(self.views.indexOf(self.view_5), _translate("Main", "PCA", None))
        self.tools.setTabText(self.tools.indexOf(self.tab), _translate("Main", "Electrodes", None))
        self.tools.setTabText(self.tools.indexOf(self.tab2), _translate("Main", "Layers", None))
        self.tools.setTabText(self.tools.indexOf(self.tab3), _translate("Main", "Units", None))
        item = self.details.verticalHeaderItem(0)
        item.setText(_translate("Main", "Project", None))
        item = self.details.verticalHeaderItem(1)
        item.setText(_translate("Main", "Dir", None))
        item = self.details.verticalHeaderItem(2)
        item.setText(_translate("Main", "VUMap", None))
        item = self.details.verticalHeaderItem(3)
        item.setText(_translate("Main", "Channel", None))
        item = self.details.verticalHeaderItem(4)
        item.setText(_translate("Main", "Files", None))
        item = self.details.horizontalHeaderItem(0)
        item.setText(_translate("Main", "Value", None))
        __sortingEnabled = self.details.isSortingEnabled()
        self.details.setSortingEnabled(False)
        item = self.details.item(0, 0)
        item.setText(_translate("Main", "-", None))
        item = self.details.item(1, 0)
        item.setText(_translate("Main", "-", None))
        item = self.details.item(2, 0)
        item.setText(_translate("Main", "-", None))
        item = self.details.item(3, 0)
        item.setText(_translate("Main", "0", None))
        item = self.details.item(4, 0)
        item.setText(_translate("Main", "[]", None))
        self.details.setSortingEnabled(__sortingEnabled)
        self.tools.setTabText(self.tools.indexOf(self.tab4), _translate("Main", "Details", None))
        self.menu_File.setTitle(_translate("Main", "&File", None))
        self.menu_Edit.setTitle(_translate("Main", "&Edit", None))
        self.menu_Help.setTitle(_translate("Main", "&Help", None))
        self.menu_View.setTitle(_translate("Main", "&View", None))
        self.toolBar.setWindowTitle(_translate("Main", "toolBar", None))
        self.action_New_Project.setText(_translate("Main", "&New Project", None))
        self.action_New_Project.setIconText(_translate("Main", "New Project", None))
        self.action_New_Project.setToolTip(_translate("Main", "Create a new project", None))
        self.action_New_Project.setShortcut(_translate("Main", "Ctrl+N", None))
        self.action_Load_Project.setText(_translate("Main", "&Load Project", None))
        self.action_Load_Project.setIconText(_translate("Main", "Load Project", None))
        self.action_Load_Project.setToolTip(_translate("Main", "Load project", None))
        self.action_Load_Project.setShortcut(_translate("Main", "Ctrl+L", None))
        self.action_Save_Project.setText(_translate("Main", "&Save Project", None))
        self.action_Save_Project.setIconText(_translate("Main", "Save Project", None))
        self.action_Save_Project.setToolTip(_translate("Main", "Save project", None))
        self.action_Save_Project.setShortcut(_translate("Main", "Ctrl+S", None))
        self.action_Quit.setText(_translate("Main", "&Quit", None))
        self.action_Quit.setToolTip(_translate("Main", "Close this application", None))
        self.action_Quit.setShortcut(_translate("Main", "Ctrl+Q", None))
        self.action_Swap.setText(_translate("Main", "Swap", None))
        self.action_Swap.setToolTip(_translate("Main", "Swap two selected units", None))
        self.action_Collapse.setText(_translate("Main", "Collapse", None))
        self.action_Collapse.setToolTip(_translate("Main", "Collapse selected unit row(s)", None))
        self.action_Recalculate_mapping.setText(_translate("Main", "Recalculate mapping", None))
        self.action_Recalculate_mapping.setToolTip(_translate("Main", "Try to find a mapping automatically", None))
        self.action_Save_as.setText(_translate("Main", "Save as", None))
        self.action_Save_as.setToolTip(_translate("Main", "Save project as", None))
        self.action_Load_connector_map.setText(_translate("Main", "Load connector map", None))
        self.action_Zoom_in.setText(_translate("Main", "Zoom in", None))
        self.action_Zoom_in.setToolTip(_translate("Main", "Zoom overview in", None))
        self.action_Zoom_in.setShortcut(_translate("Main", "Ctrl++", None))
        self.action_Zoom_out.setText(_translate("Main", "Zoom out", None))
        self.action_Zoom_out.setToolTip(_translate("Main", "Zoom overview out", None))
        self.action_Zoom_out.setShortcut(_translate("Main", "Ctrl+-", None))
        self.action_Revert_mapping.setText(_translate("Main", "Revert mapping", None))
        self.action_Revert_mapping.setToolTip(_translate("Main", "Revert current mapping to last saved", None))
        self.action_Collapse_overview.setText(_translate("Main", "Collapse overview", None))
        self.action_Collapse_overview.setToolTip(_translate("Main", "Decrease overview\'s y range", None))
        self.action_Expand_overview.setText(_translate("Main", "Expand overview", None))
        self.action_Expand_overview.setToolTip(_translate("Main", "Increase overview\'s y range", None))
        self.action_Preferences.setText(_translate("Main", "Preferences", None))
        self.action_Preferences.setToolTip(_translate("Main", "View and change preferences", None))
        self.action_About.setText(_translate("Main", "About", None))
        self.action_About.setToolTip(_translate("Main", "Information about SWAN", None))
        self.action_Tutorials.setText(_translate("Main", "Tutorials", None))
        self.action_Virtual_Units.setText(_translate("Main", "Virtual units", None))
        self.action_Virtual_Units.setToolTip(_translate("Main", "See virtual units", None))
        self.action_Export_to_csv.setText(_translate("Main", "Export to csv", None))
        self.action_Export_to_odML.setText(_translate("Main", "Export to odML", None))
        self.action_Import_from_csv.setText(_translate("Main", "Import from csv", None))
        self.action_Import_from_odML.setText(_translate("Main", "Import from odML", None))

from mplwidget2d import MplWidget2d
from mplwidget3d import MplWidget3d
from selectorwidget import SelectorWidget
from layerwidget import LayerWidget
from mplwidgetmovie import MplWidgetMovie
from myplotgrid import MyPlotGrid
from mplwidgetisi import MplWidgetIsi
from mplwidgetpca import MplWidgetPCA
from unitswidget import UnitsWidget
import icons_rc
